name: provins
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  html: ^0.15.6
  http: ^1.3.0
  # dart_eval:
  #   git:
  #     url: https://github.com/frostnova721/dart_eval

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
